### ISSUE TITLE
Changes curser position

### ISSUE THREAD

**Issue by Xenya0815** [DomiR/vscode-regreplace#1]
I used rexreplace at sublime before so I was happy to find that addon - so thx for that. But I've one problem: After saving it moves the cursor to the last line now.

To avoid that the problem is from my Regex, I have done it with the simplest possible example:

    "regreplace.commands": [
      {
        "regexp": "",
        "replace": ""
      }
    ]

**Comment by DomiR** [comment]
Thanks for the feedback 👍 

I will look into it this weekend 😄

**Comment by DomiR** [comment]
Hmm... I don't want to resort to many small replacements, as I want a singular redo step. But restoring the cursor position did not work with the following approach. I need to investigate some more...

```ts
    // store selection/cursor position
    let selection: Selection;
    if (window.activeTextEditor.document === document) {
        selection = window.activeTextEditor.selection;
    }

   // apply edits
    const edits = Promise.resolve([ new TextEdit(getMaxRange(), regreplacedText) ]);
    waitUntil(edits);

    // restore selection/cursor position
    if (selection) {
        edits.then(() => {

            // check if have enough lines for selection
            if (window.activeTextEditor.document.lineCount > selection.start.line) {
                const line = window.activeTextEditor.document.lineAt(selection.start.line);
                const character = Math.min(line.text.length - 1, selection.start.character);
                const pos = new Position(line.lineNumber, character);
                const newSelection = new Selection(pos, pos);
                window.activeTextEditor.selection = newSelection;
            }
        });
    }
```

**Comment by Xenya0815** [comment]
What's the status?

**Comment by atnbueno** [comment]
A really interesting extension, but unfortunately the cursor to the end issue renders it pretty unusable for any non-linear editing :-(

I understand wanting a single undo/redo step, but IMHO the value of that single step is much lower than losing the cursor position every time Ctrl+S is pressed (which I do every few seconds :-P).

**Comment by atnbueno** [comment]
A really interesting extension, but unfortunately the cursor-to-the-end issue renders it pretty **unusable** for any non-linear editing :-(

I understand wanting to have a single undo/redo step, but IMHO the value of that single step is much lower than **losing the cursor position** every time Ctrl+S is pressed (which I do every few seconds :-P).

For now I'm using this other extension: https://github.com/bhughes339/vscode-replacerules but I would prefer yours because of the **on-save automatic replacement** and the **filetype filtering**. 

In that other extension the cursor moves a bit laterally sometimes, but that's only slightly annoying [_UPDATE: already fixed with commit [#5ce1dd3](https://github.com/bhughes339/vscode-replacerules/commit/5ce1dd3f746622ceb6f15b5e43949705d9ab6b15)_]

Also, as a **partial workaround**, perhaps you could compare with the original text and skip the rewriting (and the cursor movement) if there have been no changes?

**Comment by atnbueno** [comment]
Followup: The extension mentioned above applies several replacements which can then be undone/redone in a single step.

**Comment by DomiR** [comment]
This should be fixed now 🎉  Please test the beta via [Beta installation](https://github.com/DomiR/vscode-regreplace/wiki/Installing-Beta-Releases).

I would like to release the update next week, if you can test it, please report back issues.

**Comment by atnbueno** [comment]
Tested. No problems. Thanks a lot! 😄

**Comment by Xenya0815** [comment]
First tests looks great! Thanks
